import Observation
import SwiftUI
import UIKit

/// The home-screen icons offered in Settings.
///
/// Artwork for all of these is generated by `Tools/MakeAppIcon.swift`; adding a
/// style means adding it there and in `project.yml`'s alternate icon list too.
enum AppIconStyle: String, CaseIterable, Identifiable {
    case adaptive
    case light
    case dark
    case neon

    var id: String { rawValue }

    var label: String {
        switch self {
        case .adaptive: return "Adaptive"
        case .light: return "Light"
        case .dark: return "Dark"
        case .neon: return "Neon"
        }
    }

    /// nil means the primary icon — what iOS shows when no alternate is set.
    var alternateName: String? {
        switch self {
        case .adaptive: return nil
        case .light: return "AppIconLight"
        case .dark: return "AppIconDark"
        case .neon: return "AppIconNeon"
        }
    }

    /// A home-screen icon can't be loaded as an image, so the picker draws a
    /// matching asset instead.
    var previewAsset: String {
        switch self {
        case .adaptive: return "AppIconPreview"
        case .light: return "AppIconLightPreview"
        case .dark: return "AppIconDarkPreview"
        case .neon: return "AppIconNeonPreview"
        }
    }
}

/// Reads and changes the home-screen icon.
///
/// iOS is the source of truth here — `alternateIconName` survives reinstalls of
/// the app's data and can be changed from outside — so the current style is
/// always read back from it rather than mirrored into UserDefaults.
@MainActor
@Observable
final class AppIconStore {
    static let shared = AppIconStore()

    private(set) var current: AppIconStyle
    private(set) var lastError: String?

    /// False on the rare device or context that forbids alternate icons; the
    /// picker hides itself rather than offering taps that can't work.
    var isSupported: Bool { UIApplication.shared.supportsAlternateIcons }

    private init() {
        let name = UIApplication.shared.alternateIconName
        current = AppIconStyle.allCases.first { $0.alternateName == name } ?? .adaptive
    }

    func select(_ style: AppIconStyle) {
        guard style != current else { return }

        // Move the tick straight away and put it back if iOS refuses, rather
        // than leaving the row unresponsive behind the system's confirmation.
        let previous = current
        current = style

        Task {
            do {
                try await UIApplication.shared.setAlternateIconName(style.alternateName)
                lastError = nil
            } catch {
                current = previous
                lastError = error.localizedDescription
            }
        }
    }
}
